apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::954746407585:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-mntj4A16t25V
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
       - system:masters
     rolearn: arn:aws:iam::954746407585:role/UdacityFlaskDeployCBKubectlRole
     username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-09-04T14:35:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1551"
  uid: 406c1ecb-bfb7-4418-89c1-24f251fe4750
